    pipeline {
        agent none
        parameters {
            string(name: 'colony-command-version', defaultValue: '0', description: 'Version to test')
            string(name: 'colony-query-version', defaultValue: '0', description: 'Version to test')
        }
        stages {
            stage('docker pull') {
                steps {
                    echo 'Docker pull...'
                    echo "Project name: ${params.colony-query-version}:${params.colony-command-version}"
                }
            }
            stage('run e2e') {
                steps {
                    echo 'run e2e...'
                }
            }
        }
    }