    pipeline {
        agent none
        parameters {
            string(name: 'version', defaultValue: '0', description: 'version to test')
            string(name: 'project', defaultValue: 'default', description: 'default name ble ble')
        }
        stages {
            stage('docker pull') {
                steps {
                    echo 'Docker pull...'
                    echo "Project name: ${params.project}:${params.version}"
                }
            }
            stage('run e2e') {
                steps {
                    echo 'run e2e...'
                }
            }
        }
    }